### PR TITLE
feat: cache s key prefix configuration

### PR DESCRIPTION
**Pull request by ezerdemello**
**Please check if the PR fulfills these requirements**
- [x ] Followed the [Contributing](https://github.com/node-cache-manager/cache-manager/blob/main/CONTRIBUTING.md) guidelines.
- [ ] Tests for the changes have been added (for bug fixes/features) with 100% code coverage.
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Includes new configuration option for create cache's keys prefix if this option is informed. If this new configuration option didn't setup nothing happens.

### CODE REVIEW

**Comment by jaredwray** [comment]
@ezerdemello thanks for the pull request. I would recommend you add this value to options instead of adding another.

**Comment by ezerdemello** [comment]
Ok!! I'll change and submit the branch. Thanks.

Em dom., 21 de abr. de 2024 13:54, Jared Wray ***@***.***>
escreveu:

**Comment by jaredwray** [comment]
@ezerdemello - great. Let me know when the change is ready.

**Comment by ezerdemello** [comment]
Hey Jared Wray,

i think that its done! Anything else send new message for me

bye!

Em ter., 23 de abr. de 2024 às 12:24, Jared Wray ***@***.***>
escreveu:

**Comment by jaredwray** [comment]
@ezerdemello - There are two things we need. The main thing is we need to get a unit test to validate this. Can you submit that? if you do I can add in the documentation for this. 

Thanks!

**Comment by zph** [comment]
This will be a nice addition @ezerdemello @jaredwray , I found myself implementing this in a custom store and having it baked into the interface will be superior. 🙇

**Comment by jaredwray** [comment]
@ezerdemello and @zph - Agreed and the last updates I can do if they arent done earlier in a week or so then will deploy.

**Pull request merged**
